### ISSUE TITLE
Activity and Group page

### ISSUE THREAD

**Issue by redperiabras** [UBP-Project/pub#24]
![image](https://user-images.githubusercontent.com/21376311/31214599-7f0092a4-a9de-11e7-8ea3-d4951f980b35.png)

@princejulius, yung background pre? gawin mo nalang na cover hehe

**Comment by arielconde** [comment]
walang cover photo yung activity

**Comment by redperiabras** [comment]
de i mean para hindi naguulit ulit yung picture.

**Comment by redperiabras** [comment]
yung parang tiled

**Comment by arielconde** [comment]
ahhh yung css na cover

**Comment by redperiabras** [comment]
yeah haha

**Comment by redperiabras** [comment]
ganon din pre sa group

**Comment by redperiabras** [comment]
@princejulius
