### ISSUE TITLE
All Activities in "My Activities" page is labeled as done

### ISSUE THREAD

**Issue by arielconde** [UBP-Project/pub#28]
![image](https://user-images.githubusercontent.com/9253848/31321900-c06d83c6-acbf-11e7-8eb0-6bb90208d7da.png)

**Comment by redperiabras** [comment]
anong nangyari pre? @acondense

**Comment by arielconde** [comment]
okay na pre nireflect ko lang yung nasa activities to myactivities page

**Comment by redperiabras** [comment]
ay sa myactivities pala to. activities nga lang pala inayos ko sorry sorry my bad haha
