### ISSUE TITLE
New Group Membership Issue

### ISSUE THREAD

**Issue by princejulius** [UBP-Project/pub#34]
If I create a group, it pins on mygroups -> joined groups.
It will have 1 group member count, but I'm neither a member nor leader when I open the modal (the one who created the group)
Siguro kasi napupunta siya doon sa 'manager' role ng group, which is hindi naman natin pinapakita na, kasi parang leader na rin yung role na yun sa group.
Since 'Manager' of the system lang naman nakakagawa ng group, siguro huwag na lang siya isama as member or leader ng newly created group.
Any opinion?

**Comment by redperiabras** [comment]
hindi naman siya kasama pero nacount lang siya as member. sige edit ko api non

**Comment by redperiabras** [comment]
Ok na

a50eaaca428d51f6114d4524cffe0053f985cbce
